---
# inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
